[pytest]
minversion = 8.0
testpaths = tests
addopts =
    -ra
    --strict-markers
    --strict-config
asyncio_mode = auto
filterwarnings =
    error
    ignore:jax.core.Primitive is deprecated.*:DeprecationWarning:(equinox|jax)(\..*)?
    ignore:datetime.datetime.utcnow\(\) is deprecated.*:DeprecationWarning:google.protobuf.internal.well_known_types
markers =
    gpu_0: marks tests that do not require a GPU
    integration: marks integration tests
    model: model id used by a test or parameter
    planner: marks tests for the planner component
    post_merge: marks tests to run after merge
    pre_merge: marks tests to run before merging
    timeout: test timeout in seconds
    unit: marks unit tests
